channels:
  - pytorch
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pymatgen==2020.8.13
  - rdkit==2020.03.5
  - openbabel==3.1.1
  - pytorch==1.6.0
  - dgl==0.5.2
